[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --allow-erase-all --always-print-stacktrace --catch-reset --catch-hardfault --chip nRF52840_xxAA"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=--nmagic",
]

[build]
target = "thumbv7em-none-eabihf"
